CapstoneProject/Roadtrip/Roadtrip/Models/Event.cs
namespace Roadtrip.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Event
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            Attendants = new HashSet<Attendant>();
        }

        [Key]
        public int EID { get; set; }

        [Required]
        public string EventName { get; set; }

        [Required]
        public string Route { get; set; }

        public DateTime Start { get; set; }

        public DateTime Finish { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendant> Attendants { get; set; }
    }

}

CapstoneProject/Roadtrip/Roadtrip/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Roadtrip.Models;
using Microsoft.AspNet.Identity;
using System.Web.Security;

namespace Roadtrip.Controllers
{
    public class EventsController : Controller
    {
        private ProfileContext db2 = new ProfileContext();

        // GET: Events
        public ActionResult Index()
        {
            return View(db2.Events.ToList());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(int? EventID)
        {
            //Gets the user's id
            var userName = User.Identity.Name;
            List<Profile> test = db2.Profiles.Where(Profiles => Profiles.UserName == userName).ToList();
            int ChristAlmightyThatTookWayTooLong = test[0].PPID;

            Attendant attendant = new Attendant();
            attendant.EventID = EventID.Value;
            attendant.UserID = ChristAlmightyThatTookWayTooLong;
            db2.Attendant.Add(attendant); //add user as attendant of event
            db2.SaveChanges();
            return RedirectToAction("Index");
        }

            // GET: Events/Details/5
            public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db2.Events.Find(id);
            ViewBag.eid = @event.EID; 
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        public JsonResult LoadCommentsEvents(string id)
        {
            int x = Int32.Parse(id); //Convert from string to int
            var comments = db2.Comments.Where(s => s.EstablishmentID == id).ToList(); //Grabs all comments for an event
            if (comments.Count() == 0)
            {
                var model = new
                {
                    EstablishmentID = id
                };

                return Json(model, JsonRequestBehavior.AllowGet);
            }

            return Json(comments, JsonRequestBehavior.AllowGet);
        }

        //parses out name from string of name, latitude, longitude and creates string of only names of establishments on the route
        public void ParseRoute(Event model)
        {
            System.Text.StringBuilder routeString = new System.Text.StringBuilder();
            int start, end;

            //Split the stored string into an array of locations
            string[] words = model.Route.Split('\n');

            //Foreach location-
            for (int i = 0; i < words.Length - 1; i++)
            {
                start = words[i].IndexOf("[Na]");
                end = words[i].LastIndexOf("[Na]");
                routeString.Append(words[i].Substring(start + 4, end - start - 4));
                if(words.Length - 2 > i)
                {
                    routeString.Append("-");
                }
            }

            model.Route = routeString.ToString();
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            Event model = new Event();
            int id = Convert.ToInt32(Request.QueryString["id"]);
            var test = db2.SavedRoutes.Where(e => e.SRID == id).ToList();
            model.Route = test[0].Route;
            ParseRoute(model);
            return View(model);
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EID,EventName,Route,Start,Finish")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db2.Events.Add(@event);
                db2.SaveChanges();
                Attendant model = new Attendant();
                var userName = User.Identity.Name;
                List<Profile> test = db2.Profiles.Where(Profiles => Profiles.UserName == userName).ToList();
                int ChristAlmightyThatTookWayTooLong = test[0].PPID;
                model.EventID = @event.EID;
                model.UserID = ChristAlmightyThatTookWayTooLong;
                db2.Attendant.Add(model);
                db2.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(@event);
        }


        // GET: Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db2.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db2.Events.Find(id);
            db2.Events.Remove(@event);
            db2.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db2.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CapstoneProject/Roadtrip/Roadtrip/Controllers/SavedRoutesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Roadtrip.DAL;
using Roadtrip.Models; 

namespace Roadtrip.Controllers
{

    public struct Route
    {
        public int SRID { get; set; }
        public string routeName { get; set; } 
        public string Username { get; set; }
        public DateTime Timestamp { get; set; }
        public List<RLocation> Locations { get; set; }
        public string Tag1 { get; set; }
        public string Tag2 { get; set; }
    }
    public struct MoreInfo
    {
        public string RouteName { get; set; }
        public string UserName { get; set; }
        public int RouteID { get; set; }
        public string tag1 { get; set; }
        public string tag2 { get; set; }
    };

public struct RLocation
    {
        public string Name { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string Id { get; set; }
    };
    [Authorize]
    public class SavedRoutesController : Controller
    {
        private SavedRoutesModel db = new SavedRoutesModel();

        [HttpPost]
        public JsonResult SaveRoute(List<RLocation> rl, string actName)
        {
            StringBuilder sb = new StringBuilder();
            SavedRoute savedRoute = new SavedRoute();
            string Rname = Request.QueryString["routeName"];
            string tag1 = Request.QueryString["tag1"];
            string tag2 = Request.QueryString["tag2"]; 
            string myName = actName;


            foreach (RLocation r in rl) 
            {
               
                sb.AppendFormat("[Na]{0}[Na] [La]{1}[La] [Lo]{2}[Lo] [Id]{3}[Id] \n",
                    r.Name, r.Latitude, r.Longitude, r.Id);
            }

            if (!db.SavedRoutes.Any())
            {
               // savedRoute.SRID = 0;
            }

                //savedRoute.SRID = db.SavedRoutes.OrderByDescending(s => s.SRID).FirstOrDefault().SRID;

            if (Request.IsAuthenticated)
                savedRoute.Username = User.Identity.Name;
            else
                savedRoute.Username = "test123@wou.com";
            savedRoute.Timestamp = DateTime.UtcNow;
            savedRoute.Route = sb.ToString();
            savedRoute.RouteName = Rname;
            savedRoute.Tag1 = tag1;
            savedRoute.Tag2 = tag2; 

            db.SavedRoutes.Add(savedRoute);
            
            try
            {
                db.SaveChanges();
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting
                        // the current instance as InnerException
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }

            return Json(new { result = "Redirect", url = Url.Action("/Details/" + savedRoute.SRID ) });
        }

        // GET: SavedRoutes
       
        public ActionResult Index()
        {
            //List<SavedRoute> sr = db.SavedRoutes.OrderByDescending(s => s.Timestamp).ToList();
            List<MoreInfo> mr = new List<MoreInfo>(); 
          
                List<SavedRoute> sr = db.SavedRoutes
                    .OrderByDescending(s => s.Timestamp)
                    .ToList();


                List<LikedRoute> lr = db.LikedRoute
              .Where(s => s.UserName.Contains(User.Identity.Name))
              .ToList();

            for (int i = 0; i <= lr.Count -1; i++)
            {
                for (int j = 0; j <= sr.Count - 1; j++)
                {
                    if (lr[i].RouteID == sr[j].SRID)
                    {
                        mr.Add(new MoreInfo { RouteName = sr[j].RouteName, UserName = sr[j].Username, RouteID = sr[j].SRID, tag1 = sr[j].Tag1, tag2 = sr[j].Tag2 }); 
                    }
                }
            }

                ViewBag.LikedList = mr;

                return View(LoadRoute(sr));
          
        }
        
        public ActionResult Saved()
        {
            List<SavedRoute> sr = db.SavedRoutes
                .Where(s => s.Username.Contains(User.Identity.Name))
                .OrderByDescending(s => s.Timestamp)
                .ToList();

            return View(LoadRoute(sr));
        }

        public void DeleteRoute()
        {
            int id = Int32.Parse(Request.QueryString["id"]);
            List<SavedRoute> sr = db.SavedRoutes
                .Where(s => s.SRID.Equals(id))
                .ToList();

            foreach (SavedRoute s in sr)
            {
                db.SavedRoutes.Remove(s);
                db.SaveChanges();
            }
        }

        public List<Route> LoadRoute(List<SavedRoute> srs)
        {
            List<Route> rls = new List<Route>();

            foreach(SavedRoute sr in srs)
            {


                rls.Add(ParseRoute(sr.Route, sr.Timestamp, sr.RouteName, sr.SRID, sr.Username, sr.Tag1, sr.Tag2)) ;
               


                //rls.Add(ParseRoute(sr.Route, sr.Timestamp, sr.SRID, sr.Username));


            }
            
            


            return rls;
        }

        public Route ParseRoute(string s, DateTime ts, string routeName, int srid, string uName, string tag1, string tag2)
        {
            Route r = new Route();
            r.Locations = new List<RLocation>();
            RLocation rl;
            int start, end;

            //Split the stored string into an array of locations
            string[] words = s.Split('\n');

            //Foreach location-
            for (int i = 0; i < words.Length - 1; i++)
            {
                //Reset our placeholder
                rl = new RLocation();

                start = words[i].IndexOf("[Na]");
                end = words[i].LastIndexOf("[Na]");
                rl.Name = words[i].Substring(start + 4, end - start - 4);

                start = words[i].IndexOf("[La]");
                end = words[i].LastIndexOf("[La]");
                rl.Latitude = double.Parse(words[i].Substring(start + 4, end - start - 4));

                start = words[i].IndexOf("[Lo]");
                end = words[i].LastIndexOf("[Lo]");
                rl.Longitude = double.Parse(words[i].Substring(start + 4, end - start - 4));

                start = words[i].IndexOf("[Id]");
                end = words[i].LastIndexOf("[Id]");
                rl.Id = words[i].Substring(start + 4, end - start - 4);

                //Repeat for others
                r.Locations.Add(rl);
            }

            r.Timestamp = ts;
            r.routeName = routeName;

            r.SRID = srid;
            //r.userName = uName;
            r.Tag1 = tag1;
            r.Tag2 = tag2; 

           // r.SRID = SRID;
            r.Username = uName;

           
            r.Username = uName; 


            return r;
        }



        // GET: SavedRoutes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SavedRoute savedRoute = db.SavedRoutes.Find(id);
            if (savedRoute == null)
            {
                return HttpNotFound();
            }
            return View(savedRoute);
        }

        // GET: SavedRoutes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SavedRoutes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SRID,Route,Timestamp,Username")] SavedRoute savedRoute)
        {
            if (ModelState.IsValid)
            {
                db.SavedRoutes.Add(savedRoute);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(savedRoute);
        }

        // GET: SavedRoutes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SavedRoute savedRoute = db.SavedRoutes.Find(id);
            if (savedRoute == null)
            {
                return HttpNotFound();
            }
            return View(savedRoute);
        }

        // POST: SavedRoutes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SRID,Route,Timestamp,Username")] SavedRoute savedRoute)
        {
            if (ModelState.IsValid)
            {
                db.Entry(savedRoute).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(savedRoute);
        }

        // GET: SavedRoutes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {

CapstoneProject/Roadtrip/Roadtrip/Views/Events/Create.cshtml
@model Roadtrip.Models.Event

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EventName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Route, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Route, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Route, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Start, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Finish, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Finish, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Finish, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CapstoneProject/Roadtrip/Roadtrip/Views/Events/Delete.cshtml
@model Roadtrip.Models.Event

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Route)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Route)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Finish)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Finish)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CapstoneProject/Roadtrip/Roadtrip/Views/Events/Details.cshtml
@model Roadtrip.Models.Event

@{
    ViewBag.Title = "Details";
    var eid = ViewBag.EID;
    <script src="~/Scripts/EventDetails.js"></script>
    <script>
            EventComments(@ViewBag.eid);
    </script>
}

<h2>Details</h2>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Route)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Route)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Finish)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Finish)
        </dd>

    </dl>
</div>

<div id="comments"></div>
<a href="Create/Comments/1" id="createComment" target="_blank, width = '400px', height = '400px'">Add Comment</a>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EID }) |
    @Html.ActionLink("Back to List", "Index")
</p>



@Scripts.Render("~/Scripts/EventDetails.js")

CapstoneProject/Roadtrip/Roadtrip/Views/Events/Index.cshtml
@model IEnumerable<Roadtrip.Models.Event>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create Event", "Saved", "SavedRoutes")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Route)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Start)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Finish)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.EventName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Route)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Start)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Finish)
    </td>


    <td>
        @using (Html.BeginForm("Index", "Events"))
        {
            @Html.AntiForgeryToken()

            <input type="hidden" name="EventID" value="@item.EID" />
            <input type="submit" value="Attend" />
        }

        @Html.ActionLink("Details", "Details", new { id = item.EID })
    </td>
</tr>
}

</table>