CapstoneProject/Roadtrip/Roadtrip/Controllers/RoutesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using System.IO;
using System.Net;
using Newtonsoft.Json.Linq;
using System.Web.Helpers;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using Roadtrip.Models.ViewModels;
using System.Text;
using Roadtrip.Controllers;
using Roadtrip.Models;
using Roadtrip.DAL;

namespace Roadtrip.Controllers
{
    [Authorize]
    public class RoutesController : Controller
    {
       // ApplicationDbContext db = new ApplicationDbContext();
        CommentsModel db1 = new CommentsModel();

        ProfileContext db2 = new ProfileContext();


        private SavedRoutesModel db = new SavedRoutesModel();


        // GET: Routes
        [HttpGet]
        public ActionResult Index()
        {
            
            string path = Server.MapPath("~/Uploads/");
            if (System.IO.File.Exists(path + User.Identity.Name + ".jpeg"))
            {
                ViewBag.loggedIn = true;
            }
            else
                ViewBag.loggedIn = false;
            return View();
        }

        public ActionResult HowTo()
        {
            return View();
        }

        public ActionResult getLikeEstablishments()
        {
            List<LikedEstablishments> le = db.LikedEstablishments
             .Where(s => s.UserName.Contains(User.Identity.Name)).ToList();

            return new ContentResult
            {
                // serialize C# object "commits" to JSON using Newtonsoft.Json.JsonConvert
                Content = JsonConvert.SerializeObject(le),
                ContentType = "application/json",
                ContentEncoding = System.Text.Encoding.UTF8
            };

        }

        public ActionResult Create()
        {

            string path = Server.MapPath("~/Uploads/");
            if (System.IO.File.Exists(path + User.Identity.Name + ".jpeg"))
            {
                ViewBag.loggedIn = true;
            }
            else
            {
                ViewBag.loggedIn = false;
            }

            List<LikedEstablishments> le = db.LikedEstablishments
             .Where(s => s.UserName.Contains(User.Identity.Name))
             .ToList();

            ViewBag.LikedList = le;


            return View();
        }

        public JsonResult LoadComments(string id)
        {
            var comments = db1.Comments.Where(s => s.EstablishmentID == id).ToList(); //grabs all comments for one establishment
            Trace.WriteLine(comments);
            if(comments.Count() == 0)
            {
                var model = new
                {
                    EstablishmentID = id
                };
                
                return Json(model, JsonRequestBehavior.AllowGet);
            }

            return Json(comments, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadEvents(int id)
        {
            //Grabs all events a user is attending
            var events = from a in db2.Attendant
                         join e in db2.Events on a.EventID equals e.EID
                         where a.UserID == id
                         select new { a.Event.EventName,  a.Event.Start };

            Trace.WriteLine(events);

            return Json(events, JsonRequestBehavior.AllowGet);
        }



        public JsonResult GetEstablishment()
        {
            string city = Request.QueryString["city"];
            string state = Request.QueryString["state"];
            string term = Request.QueryString["name"];
            string radius = Request.QueryString["numbers"];
            string key = System.Web.Configuration.WebConfigurationManager.AppSettings["YelpKey"];
            string uri = "https://api.yelp.com/v3/businesses/search?location=" + city + "," + state + "&radius=" + radius + "&term=" + term;
            string data = SendRequest(uri, key);

            JObject test = JObject.Parse(data);
            List<string> names = new List<string>();
            List<double> index = new List<double>();
            List<double> ratings = new List<double>();
            List<decimal> longi = new List<decimal>();
            List<decimal> lati = new List<decimal>();
            List<string> BusinessID = new List<string>();
            int count = (int)test["total"];

            if (count > 20)
            {
                count = 20;
            }

            for (int i = 0; i < count; i++)
            {
                index.Add(i);
                ratings.Add((double)test["businesses"][i]["rating"]);
                names.Add(((string)test["businesses"][i]["name"]).ToString());
                lati.Add((decimal)test["businesses"][i]["coordinates"]["latitude"]);
                longi.Add((decimal)test["businesses"][i]["coordinates"]["longitude"]);
                BusinessID.Add((string)test["businesses"][i]["id"]);
            }


            var FinalList = new
            {
                name = names,
                rating = ratings,
                indexs = index,
                latitude = lati,
                longitude = longi,
                id = BusinessID,
                total = count
            };

            return Json(FinalList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDetails()
        {
            string ID = Request.QueryString["id"];
            Console.WriteLine(ID);
            string key = System.Web.Configuration.WebConfigurationManager.AppSettings["YelpKey"];
            Console.WriteLine(key);
            string uri = "https://api.yelp.com/v3/businesses/" + ID;
            string data = SendRequest(uri, key);

            JObject test = JObject.Parse(data);

            List<string> name = new List<string>();
            List<double> rating = new List<double>();
            List<string> img = new List<string>();
            List<string> phone = new List<string>();
            List<string> address = new List<string>();
            List<string> city = new List<string>();
            List<string> state = new List<string>();
            List<string> zipcode = new List<string>();
            //List<string> ids = new List<string>();

            name.Add((string)test["name"]);
            rating.Add((double)test["rating"]);
            img.Add((string)test["image_url"]);
            phone.Add((string)test["phone"]);
            address.Add((string)test["location"]["address1"]);
            city.Add((string)test["location"]["city"]);
            state.Add((string)test["location"]["state"]);
            zipcode.Add((string)test["location"]["zip_code"]);
            //ids.Add((string)test["id"]);

            var FinalList = new
            {
                id = ID,
                names = name,
                ratings = rating,
                image = img,
                phones = phone,
                addresss = address,
                citys = city,
                states = state,
                zipcodes = zipcode
            };
            return Json(FinalList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetMoreDetails()
        {
            string ID = Request.QueryString["id"];
            Console.WriteLine(ID);
            string key = System.Web.Configuration.WebConfigurationManager.AppSettings["YelpKey"];
            Console.WriteLine(key);
            string uri = "https://api.yelp.com/v3/businesses/" + ID +"/reviews";
           
            string data = SendRequest(uri, key);

            JObject test = JObject.Parse(data);

            List<string> texts = new List<string>();
            List<int> ratings = new List<int>();
            List<string> img = new List<string>();
            List<string> names = new List<string>();

            for (int i = 0; i < 3; i++)
            {
                texts.Add((string)test["reviews"][i]["text"]);
                ratings.Add((int)test["reviews"][i]["rating"]);
                img.Add((string)test["reviews"][i]["user"]["image_url"]);
                names.Add((string)test["reviews"][i]["user"]["name"]);
            }



            var FinalList = new
            {
               
                text = texts,
                rating = ratings,
                image = img,
                name = names
            };
            return Json(FinalList, JsonRequestBehavior.AllowGet);
        }

        private string SendRequest(string uri, string key)

        {

            Debug.WriteLine(uri);

            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(uri);

            request.Headers.Add("Authorization", "Bearer " + key);

            request.Accept = "application/json";



            string jsonString = null;



            // TODO: You should handle exceptions here

            using (WebResponse response = request.GetResponse())

            {

                Stream stream = response.GetResponseStream();

                StreamReader reader = new StreamReader(stream);

                jsonString = reader.ReadToEnd();

                reader.Close();

                stream.Close();

            }

            return jsonString;

        }

        public ActionResult DisplayInfo(string myInfo, string city)
        {
            string request = Request.QueryString["myInfo"];
            string myCity = Request.QueryString["city"];
            string myState = Request.QueryString["state"];
            string myKey = System.Web.Configuration.WebConfigurationManager.AppSettings["OpenCageKey"];
            string yelpKey = System.Web.Configuration.WebConfigurationManager.AppSettings["YelpKey"]; 


            /*Parsing and restructuring the place element*/
            string[] words = myInfo.Split(' ');
            string test = words[0];
            for (int i = 1; i <= words.Length - 1; i++)
            {
                test = test + "+" + words[i];
            }
            /*Parsing and restructuring the City*/

CapstoneProject/Roadtrip/Roadtrip/Views/Shared/CreateRouteLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Roadtrip</title>
    @Styles.Render("~/Content/Site.css")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    @{
        string truncName = User.Identity.Name;
        //if (truncName.Length > 0)
        //{
        //truncName = truncName.Substring(0, truncName.IndexOf("@"));
        //}
    }


</head>
<body style="background-color: black;">
    <div id="fb-root"></div> <!--for facebook sharing button-->
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v6.0"></script>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark" style="height: 9vh;">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Home")">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Create", "Routes")">Create a Route</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "SavedRoutes")">View Routes</a>
                </li>
            </ul>
        </div>
        <div class="mx-auto order-0">
            <a class="navbar-brand mx-auto" href="@Url.Action("Index", "Home")">-DIGITAL HIJINKS CAPSTONE-</a>
        </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">

            @if (Request.IsAuthenticated)
            {
                using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "nav navbar-nav ml-auto" }))
                {
                    @Html.AntiForgeryToken()
                    var name = "default.jpg";
                    string path = Server.MapPath("~/Uploads/");
                    if (System.IO.File.Exists(path + User.Identity.Name + ".jpeg"))
                    {
                        name = User.Identity.Name + ".jpeg?r=" + DateTime.Now.Ticks.ToString();
                    }
                    <li class="nav-item">
                        <div class="nav-link" style="color:rgba(255, 255, 255, 0.5);">Hello, @User.Identity.Name!</div>
                    </li>
                    <li class="nav-item">
                        <a href="/Profiles/Details/@truncName"><img src="~/Uploads/@name" class="profilepic-navbar" /></a>
                    </li>
                    <li class="nav-item">
                        <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="dropdown-menu dropdown-menu-right" style="z-index: 1500;">
                            <a class="dropdown-item" href="/Manage/Index">My Account</a>
                            <a class="dropdown-item" href="/SavedRoutes/Saved">Saved Routes</a>
                            <a class="dropdown-item" href="/Manage/ChangePassword">Change Password</a>
                            <a class="dropdown-item" href="/Manage/ChangeUserName">Change UserName</a>
                            <a class="dropdown-item" href="/Account/Edit">Edit Account</a>
                            <a class="dropdown-item" href="/Profiles/Details/@truncName">Profile</a>
                            <a class="dropdown-item disabled" href="#">Settings</a>
                            <a class="dropdown-item" href="javascript:document.getElementById('logoutForm').submit()">Logout</a>
                        </div>
                    </li>

                }
            }
            else
            {
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Register", "Account")">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Login", "Account")">Login</a>
                    </li>
                </ul>
            }

        </div>
    </nav>

    <div>
        @RenderBody()
    </div>
</body>
</html>

CapstoneProject/Roadtrip/Roadtrip/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Roadtrip</title>
    @Styles.Render("~/Content/Site.css")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    @{ 
        string truncName = User.Identity.Name;
        //if (truncName.Length > 0)
        //{
            //truncName = truncName.Substring(0, truncName.IndexOf("@"));
        //}
    }


</head>
<body>
    <div id="fb-root"></div> <!--for facebook sharing button-->
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v6.0"></script>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Home")">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Create", "Routes")">Create a Route</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "SavedRoutes")">View Routes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Events", "Routes")">My Events</a>
                </li>
            </ul>
        </div>
        <div class="mx-auto order-0">
            <a class="navbar-brand mx-auto" href="@Url.Action("Index", "Home")">-DIGITAL HIJINKS CAPSTONE-</a>
        </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">

            @if (Request.IsAuthenticated)
            {
                using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "nav navbar-nav ml-auto" }))
                {
                    @Html.AntiForgeryToken()
                    var name = "default.jpg";
                    string path = Server.MapPath("~/Uploads/");
                    if (System.IO.File.Exists(path + User.Identity.Name + ".jpeg"))
                    {
                        name = User.Identity.Name + ".jpeg?r=" + DateTime.Now.Ticks.ToString();
                    }
                    <li class="nav-item">
                        <div class="nav-link" style="color:rgba(255, 255, 255, 0.5);">Hello, @User.Identity.Name!</div>
                    </li>
                    <li class="nav-item">
                        <a href="/Profiles/Details/@truncName"><img src="~/Uploads/@name" class="profilepic-navbar" /></a>
                    </li>
                    <li class="nav-item">
                        <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="dropdown-menu dropdown-menu-right" style="z-index: 1500;">
                            <a class="dropdown-item" href="/Manage/Index">My Account</a>
                            <a class="dropdown-item" href="/SavedRoutes/Saved">Saved Routes</a>
                            <a class="dropdown-item" href="/Manage/ChangePassword">Change Password</a>
                            <a class="dropdown-item" href="/Manage/ChangeUserName">Change UserName</a>
                            <a class="dropdown-item" href="/Account/Edit">Edit Account</a>
                            <a class="dropdown-item" href="/Profiles/Details/@truncName">Profile</a>
                            <a class="dropdown-item disabled" href="#">Settings</a>
                            <a class="dropdown-item" href="javascript:document.getElementById('logoutForm').submit()">Logout</a>
                        </div>
                    </li>

                }
            }
            else
            {
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Register", "Account")">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Login", "Account")">Login</a>
                    </li>
                </ul>
            }

        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr style="border-color: #474747;" />
        <footer>
            <p style="text-align: center;">&copy; @DateTime.Now.Year - Digital Hijinks</p>
            <div class="fb-share-button" data-href="https://dhcdev.azurewebsites.net/" data-layout="button" data-size="small">
                <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdhcdev.azurewebsites.net%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a>
            </div>
            <div class="twitterHelper">
                <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="Come Plan a road trip!" data-url="https://dhcdev.azurewebsites.net/" data-show-count="false">Tweet</a>
                <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>
        </footer>
    </div>
</body>
</html>