Milestone 3/ClassProject/ClassProject/Controllers/AthletesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClassProject.Models;

namespace ClassProject.Controllers
{
    public class AthletesController : Controller
    {
        private ClassContext db = new ClassContext();

        // GET: Athletes
        public ActionResult Index()
        {
            return View(db.Athletes.ToList());
        }

        public ActionResult Search()
        {
            return View(db.Athletes.ToList());
        }

        [HttpPost]
        public ActionResult Search(string Search)
        {
            //var athletes = db.Athletes.Include(s => s.Name).Include(s => s.DOB).Include(s => s.AthleteTeams); 
            var athletes = db.Athletes.Where(s => s.Name.Contains(Search));

            return View(athletes.ToList());
        }


        // GET: Athletes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Athlete athlete = db.Athletes.Find(id);
            if (athlete == null)
            {
                return HttpNotFound();
            }

            var times = db.Times.Where(s => s.AthleteID.Equals(athlete.AID));

            ViewBag.times = times.ToList();
            return View(athlete);
        }

        // GET: Athletes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Athletes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AID,Name,DOB")] Athlete athlete)
        {
            if (ModelState.IsValid)
            {
                db.Athletes.Add(athlete);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(athlete);
        }

        // GET: Athletes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Athlete athlete = db.Athletes.Find(id);
            if (athlete == null)
            {
                return HttpNotFound();
            }
            return View(athlete);
        }

        // POST: Athletes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AID,Name,DOB")] Athlete athlete)
        {
            if (ModelState.IsValid)
            {
                db.Entry(athlete).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(athlete);
        }

        // GET: Athletes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Athlete athlete = db.Athletes.Find(id);
            if (athlete == null)
            {
                return HttpNotFound();
            }
            return View(athlete);
        }

        // POST: Athletes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Athlete athlete = db.Athletes.Find(id);
            db.Athletes.Remove(athlete);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PrivacyPolicy()
        {
            return View();
        }
        public ActionResult FAQ()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Milestone 3/ClassProject/ClassProject/Controllers/TimesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClassProject.Models;
using ClassProject.Models.ViewModels;

namespace ClassProject.Controllers
{
    public class TimesController : Controller
    {
        private ClassContext db = new ClassContext();

        // GET: Times
        public ActionResult Index()
        {
            var times = db.Times.Include(t => t.Athlete).Include(t => t.Event);
            return View(times.ToList().OrderByDescending(r => r.Athlete.Name).Distinct());
        }

        // GET: Times/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Time time = db.Times.Find(id);
            if (time == null)
            {
                return HttpNotFound();
            }
            /*var my = db.Times.Join(db.Athletes.Where(
                r => r.AID == time.AthleteID),
                e => e.AthleteID, r => r.AID,
                (e, r) => new { e, r }).Select( m => new athTimeViewModel
                {
                   
                    Times = m.r.Times

                }) ;*/
            var mytimes = db.Times.Where(a => a.AthleteID == time.AthleteID).Include(t => t.Athlete).Include(t => t.Event); 
            
            ViewBag.tam = time.Athlete.Name;
           

            return View(mytimes.ToList());
        }

        // GET: Times/Create
        public ActionResult Create()
        {
            ViewBag.AthleteID = new SelectList(db.Athletes, "AID", "Name");
            ViewBag.EventID = new SelectList(db.Events, "EID", "EID");
            return View();
        }

        // POST: Times/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TID,AthleteID,EventID,Time1")] Time time)
        {
            if (ModelState.IsValid)
            {
                db.Times.Add(time);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AthleteID = new SelectList(db.Athletes, "AID", "Name", time.AthleteID);
            ViewBag.EventID = new SelectList(db.Events, "EID", "EID", time.EventID);
            return View(time);
        }

        // GET: Times/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Time time = db.Times.Find(id);
            if (time == null)
            {
                return HttpNotFound();
            }
            ViewBag.AthleteID = new SelectList(db.Athletes, "AID", "Name", time.AthleteID);
            ViewBag.EventID = new SelectList(db.Events, "EID", "EID", time.EventID);
            return View(time);
        }

        // POST: Times/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TID,AthleteID,EventID,Time1")] Time time)
        {
            if (ModelState.IsValid)
            {
                db.Entry(time).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AthleteID = new SelectList(db.Athletes, "AID", "Name", time.AthleteID);
            ViewBag.EventID = new SelectList(db.Events, "EID", "EID", time.EventID);
            return View(time);
        }

        // GET: Times/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Time time = db.Times.Find(id);
            if (time == null)
            {
                return HttpNotFound();
            }
            return View(time);
        }

        // POST: Times/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Time time = db.Times.Find(id);
            db.Times.Remove(time);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Milestone 3/ClassProject/ClassProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

    </head>
    <body id="mybody">
        <div class="wrapper">
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                    </div>
                    <div class="navbar-collapse collapse" id="totalnav">
                        <ul class="nav navbar-nav" id="mynav">
                            <li class="navbar-title" id="nbt">Swimming Race Tracker</li>
                            <li class="button">@Html.ActionLink("Home", "Index", "Home")</li>
                            <li class="button">@Html.ActionLink("FAQ", "FAQ", "Athletes")</li>
                            <li class="button">@Html.ActionLink("Privacy Policy", "PrivacyPolicy", "Athletes")</li>
                            <li class="button">@Html.ActionLink("Login", "Login", "Account")</li>
                            <li class="button">@Html.ActionLink("Make an Account", "Register", "Account", new { area = "" }, new { @class = "nav-bar-button" })</li>
                            <li class="button">@Html.ActionLink("Stats", "Index", "Times")</li>
                            <li class="button">@Html.ActionLink("Athlete Search", "Search", "Athletes")</li>
                        </ul>

                    </div>
                </div>
            </div>
            <div class="container body-content">
                @RenderBody()
                <hr />
            </div>
        </div>

        <footer>
            <div class="container-fluid">
                <div class="row">
                    <ul style="float:right" class="button">
                        <li class="button">
                            @Html.ActionLink("FAQ", "FAQ", "Athletes", new { area = "" }, new { @style = "color:black" }) |
                            @Html.ActionLink("Privacy Policy", "PrivacyPolicy", "Athletes", new { area = "" }, new { @style = "color:black" })
                        </li>
                    </ul>
                    <p>&copy; @DateTime.Now.Year - Our Project</p>

                </div>
            </div>
        </footer>


        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>

</html>